### ISSUE TITLE
Make container registry configurable

### ISSUE THREAD

**Issue by 3keyroman** [3KeyCompany/CZERTAINLY-Helm-Charts#10]
Currently the `image` section in the `values.yaml` has the following structure:
```yaml
image:
  repository: 3keycompany/czertainly-core
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
```

However, it would be helpful to extend this configuration with `registry` in case the images are stored in different registry. Although the repository can contain also registry in its name, it would be more user friendly if the registry can be also configured as `global` parameter and set it for all subcharts.

The proposed change is to have:
```yaml
image:
  # default registry name
  registry: docker.io
  repository: 3keycompany/czertainly-core
  # overrides the image tag whose default is the chart appVersion.
  tag: ""
  # the digest to be used instead of the tag
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
```
