### ISSUE TITLE
securityContext hardening of charts

### ISSUE THREAD

**Issue by 3keyroman** [3KeyCompany/CZERTAINLY-Helm-Charts#16]
The `securityContext` should be defined for every chart that will provide hardening.
At least the following should be implemented as part of the `securityContext`:
- disallow privileged = do not allow pods to specify `securityContext.privileged` or `allowPrivilegeEscallation`
- disallow root user = define `runAsNonRoot` or `runAsUser > 0` in `securityContext`
- disallow `sysctls` = disallow changing kernel parameters of worker nodes = cannot define `sysctls` in `securityContext`
- require read only root filesystem = pods must define, that their root filesystem (from docker image) is mounted readonly (`readOnlyRootFilesystem: true` in `securityContext`)

There should be options for ephemeral volume that is needed in some cases to have read-only filesystem.
Memory:
```yaml
        - name: ephemeral
          emptyDir:
            sizeLimit: "1Mi"
            medium: "Memory"
```
Storage:
```yaml
        - name: ephemeral
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                # configurable option to select storage class
                storageClassName: "scratch-storage-class"
                resources:
                  requests:
                    storage: 1Mi
```
