### ISSUE TITLE
Implement support for producing OpenTelemetry signals (traces, metrics, logs)

### ISSUE THREAD

**Issue by 3keyroman** [3KeyCompany/CZERTAINLY-Helm-Charts#169]
The OpenTelemtry is becoming a standard for observability.
CZERTAINLY Helm chart and its subcharts should support OTEL for collecting traces, metrics, and logs.

> **The scope of this issue is to start producing signals, when enabled. Collecting and using signals are out of scope of this issue.**

OTEL support should be configurable on global and local (chart) level. When the global temeletry is enabled, all components that supports OTEL should enable it also.

Through the configuration, user should be able to select signals that should be produced and collected:
- traces
- metrics
- logs

For example:
```
global:
  opentelemetry:
    enabled: true
    signals:
      traces:
        enabled: true
      metrics:
        enabled: true
      logs:
        enabled: true
```

Components should produce only signals that are configured (not true for logs, logs are by default produced in the system).
