### ISSUE TITLE
Split repository and image name for charts

### ISSUE THREAD

**Issue by 3keyroman** [3KeyCompany/CZERTAINLY-Helm-Charts#95]
We can define `global.image.registry` parameter to globally change the docker registry for all charts.
However, the repository name is sill locally defined and in some case it needs to be changed also on the global level (for example when we maintain private docker registry with custom repositories/projects).

It would be helpful if the current `image.repository` parameter is split into `image.repository` and `image.name`. Then we can create `global.image.repository` that will be applied to all charts without need to write it specifically for all of them.

An example:
```
global:
  image:
    registry: ""
    repository: ""

image:
  # default registry name
  registry: docker.io
  repository: 3keycompany
  name: czertainly-core
  tag: 2.7.1
```

This will produce image as `docker.io/3keycompany/czertainly-core:2.7.1`

```
global:
  image:
    registry: myregistry.com
    repository: ""

image:
  # default registry name
  registry: docker.io
  repository: 3keycompany
  name: czertainly-core
  tag: 2.7.1
```

Will produce `myregistry.com/3keycompany/czertainly-core:2.7.1`

```
global:
  image:
    registry: myregistry.com
    repository: czertainly/project

image:
  # default registry name
  registry: docker.io
  repository: 3keycompany
  name: czertainly-core
  tag: 2.7.1
```

Will produce `myregistry.com/czertainly/project/czertainly-core:2.7.1`
